### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by MarBGamer** [manatlan/guy#1]
I have a question. Is guy secure enough to be used as an online website? Like I don't want people going through the python code or looking at other files on the server. But I'd love to be able to use guy because it is exactly what I need for my little project!

**Comment by manatlan** [comment]
Guy is as solid as tornado.

On the host server. Consider to put your guy behind a reverse proxy (like nginx), to use ssl for your http. 

BTW, currently, you can shutdown the server, using the js on clientside (press F12, type "self.exit()") .. It's amazing, but I should provide a way to block that feature, for server mode ;-)

try: https://starter-guy-vuejs.glitch.me/ ... but glitch restart the process ;-)

**Comment by MarBGamer** [comment]
Thank you very much! I was already planning on putting it behind nginx and using SSL so that shouldn't be a problem. Thanks for you amazing work!
