### ISSUE TITLE
electron

### ISSUE THREAD

**Issue by megohannes** [manatlan/guy#10]
Hi,
just a question: Do you think it would be possible or even a good idea to make guy work with the electron browser - I mean still have python as the server and backend but use the electron browser to enable us to more easily have control over how the browser window behaves (menubar, shortcuts, frame, ...).
Or is that what cef would be for? I have no experience with cef so I'm sorry if that was obvious.

**Comment by manatlan** [comment]
Hi,
Cef is like electron, but on lower level side.
I don't think it's a good idea. The twos are based on chromium. 
The final result is the same, but cef is more flexible.

**Comment by megohannes** [comment]
thank you.
that makes sense.

**Comment by manatlan** [comment]
But understand, that guy doesn't give you the full power of a cefpython/electron. It's not the purpose.
There is a layer between le html/js and the python code : all communications is done magically thru websocket (no native call from js to py ..; like cef or electron provides)
This layer permits to run your app in a classical installed chrome app, or thru a webserver (like a classic web site) ... or in a cef instance (only, to avoid the need of an installed chrome app) .. or to run it in a kivy/webview (chrome) instance ... (without the need to know kivy!)
