### ISSUE TITLE
DEBUG on by default

### ISSUE THREAD

**Issue by icarito** [manatlan/guy#12]
Hi,
It was driving me crazy in latest guy debugging logging was on.
I managed to change setting to setLevel(logging.ERROR) in guy.py.
But this should be off by default and a configurable setting documented.
Thanks for your work!

**Comment by manatlan** [comment]
Hi .... I don't understand ....
In current release (and olders) : "debugging" is off by default ...
to enable it, you should set "log=True" when calling .serve(), .run() ....
no ?

**Comment by icarito** [comment]
No, debugging is on by default, at least in Guy version 0.5.3 which is 
what I'm using.
I disabled it in guy.py locally by editing line 57 from DEBUG to ERROR.

**Comment by icarito** [comment]
Here, it changed 2 months ago:

<https://github.com/manatlan/guy/commit/67854cfe811b0233e06b880dded9e70587a5d297>

:-)

Thanks for Guy!

**Comment by manatlan** [comment]
and ... is the 0.5.5 right for you ?

**Comment by icarito** [comment]
I'll check it and let you know! Didn't find a release or a tag in the 
repo so I guess from NPM?

**Comment by manatlan** [comment]
The 0.5.5 is on GitHub & https://pypi.org/project/guy/

**Comment by icarito** [comment]
Yeah sorry I meant Pypi not npm!

**Comment by icarito** [comment]
I just tried it and it still exhibits the same flaw!


For what it's worth, my code lives at 
<https://gitlab.com/fuentelibre/super-8/> and is deployed (with the 
workaround described) at <https://super-8.educa.juegos/>

**Comment by manatlan** [comment]
> I just tried it and it still exhibits the same flaw!

I don't understand what is this flaw ...

**Comment by icarito** [comment]
Here's a simple program that causes debugging messages to appear on button press:
```
from guy import Guy

class ShowFlaw(Guy):
    """
    <button onclick="self.show_flaw()">PUSH</button>
    (and see the javascript console debugging)
    """

    def show_flaw(self):
        return "This will log into javascript console."

ShowFlaw().run()
```

**Comment by icarito** [comment]
And here's the JS console:
![image](https://user-images.githubusercontent.com/199755/78842086-b5457380-79c4-11ea-8057-c0094f765549.png)

This is with Guy 0.5.5.

**Comment by manatlan** [comment]
the 0.5.6 fix that issue (here & on pypi)
