### ISSUE TITLE
fail in the 'Favicon' 

### ISSUE THREAD

**Issue by dbsantos1981** [manatlan/guy#24]
My 'favicon' icon is not showing. The default icon appears instead of my icon. What is the correct procedure to display my icon? I put the 'favicon.ico' file in the 'static' folder.

Guy version 0.4.0 works (my first project).
Guy version 0.7.3 doesn't work (my current project)

I thank you in advance for your help.

**Comment by manatlan** [comment]
You're right ...

Since recent versions ... guy handle/override the http request for the "favicon.ico".
So putting a favicon.ico in your static will have no effect ;-(

Currently, I set my "fav icon" with a classic html tag in the header (so your browser will not try to find a favicon.ico) ...

tells me if it helps you ...

**Comment by dbsantos1981** [comment]
Hi!

It's works! Thank you so much.

I put this line in the main html file

<link rel="icon" type="image/png" href="/img/favicon.ico">

*Could you help me again?*

I would like to show the Windows user at this page. In the previous
version, it worked normally, my code was:

class SapTec(guy.Guy):

    def init(self):
        #carrega os dados iniciais
        usuario = Usuario.get_nome_chave(Usuario)
        sysinfo = SysInfo.sys_info(SysInfo)
        print('oi')
        print(usuario)

        async def __get_usuario():
            await self.emit("nomeUsuario", usuario)


But now it doesn't work. What should I do?

Thanks again.


Em ter., 2 de jun. de 2020 às 17:26, manatlan <notifications@github.com>
escreveu:

**Comment by dbsantos1981** [comment]
The first problem (about the icon) has been solved.

Regarding the second problem, I decided to change the logic of the code, using the information in another way.

Thank you and congratulations for the GUY.
