### ISSUE TITLE
Failed to execute script app

### ISSUE THREAD

**Issue by dbsantos1981** [manatlan/guy#26]
Greetings,

If I generate the app's executable on windows with **pyinstaller** using the _**--noconsole**_ option, the message '_Failed to execute script App_' appears when running the generated exe application, and the app does not work.

If I generate the executable without this option, the system works normally, however, **the console window appear**s.

I would like, as in previous versions, that compilation **without** the console would work. Have you seen this error in any situation? Do you have any tips to give me?

**Comment by JeswinSunsi** [comment]
Ah yes, there's a workaround to this which I've used.
```
def hideConsole():
  whnd = ctypes.windll.kernel32.GetConsoleWindow()
  if whnd != 0:
     ctypes.windll.user32.ShowWindow(whnd, 0)
```
You can then call hideConsole() and the console gets hidden. Also, do import ctypes.

**Comment by dbsantos1981** [comment]
## It works! Thank you very much.

I tested this solution in two possibilities and both worked:

### First:
I put the function call at the beginning of the code as below:
```
if __name__ == "__main__":
     # hide the console
     SapTec.hide_console(SapTec)
```
### Second:
I put the function call in the HTML file after loading all its content.
```
<script>
    self.hide_console();
</script>
```
## Thanks again.
