### ISSUE TITLE
charset in <head> isn't interpreted

### ISSUE THREAD

**Issue by inillaug** [manatlan/guy#4]
Hello,

I put <meta charset="UTF-8"> in <head> but the character "è" appear as "Ã¨". If open the html without loading webserver the character "è" is correct.

**Comment by manatlan** [comment]
Hi,

It appears that you are on windows, and you was using a non-utf8 editor, like notepad ... no ?

Sorry for that, but currently, html's content can only be utf8 (and no windows-1252 or consorts) ...

Try the same thing, with a ut8's ready editor (set the file's encoding to utf8) .. and tell me

**Comment by inillaug** [comment]
Hello manatlan, the html file is already in UTF-8. I've opened it with "Notepad++" in Windows7.
The head content is already meta-tagged as UTF-8.

  meta http-equiv="Content-Type" content="text/html; charset=utf-8" 
  meta charset="UTF-8"

**Comment by manatlan** [comment]
could you post me your html file ? to have a look

**Comment by manatlan** [comment]
I've understand ;-)
You've setted your meta tag as if it was utf8 ...
But, on windows, default encoding is "mbcs" (cp-1252 in europe) : so your content is windows-1252 ! try to set your meta as "Windows-1252" .. and it should work (or configure your notepad++ to encode your text content as utf8).
In fact : your meta tag should be the same as the content encoding (if it differs, like you, you encounter this kind of troubble)

I close ...
feel free to reopen if not

**Comment by inillaug** [comment]
Hello,

No way.

If I open the html file directly in Firefox the viewing is correct.

If I open the html file trough guy the charset is wrong.

*Matteo Guallini*
Cellulare: +393338922541
Via Gaetano Strigelli 13, 20135 Milano, Italia 
<http://maps.google.com/maps?f=q&source=s_q&hl=it&geocode=&q=Via+Gaetano+Strigelli,+Milano+13,+Italia&sll=45.455868,9.217181&sspn=0.007556,0.019011&ie=UTF8&hq=&hnear=Via+Gaetano+Strigelli,+13,+20135+Milano,+Lombardia,+Italia&ll=45.456925,9.218838&spn=0.007556,0.019011&z=16&iwloc=A>
Il 12/02/2020 21:29, manatlan ha scritto:

**Comment by inillaug** [comment]
Hello,
No way.
If I open the html file directly in Firefox, the viewing is correct.
If I open the html file trough guy -> Firefox, the wiewing is wrong.

**Comment by manatlan** [comment]
Hi, glad to hear you again ...

Can you provide a version of your HTML file, so I could see the trouble, and could fix it ?

**Comment by inillaug** [comment]
Hi, how can I send you the file?

**Comment by manatlan** [comment]
you can attach a file ... here in a comment !

**Comment by inillaug** [comment]
`<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta charset="UTF-8">
	<title>Ciao Ciao!</title>
	
<script type="application/javascript" src="guy.js"></script>
	
</head>
<body>
<h1>Ciao Mondo!</h1>

<p>Questa è la nostra prima pagina HTML!</p>

</body>
</html>
`

**Comment by manatlan** [comment]
can your repost a comment, with the file embedded in the msg
(by just dragging it from your file folder to the comment in your browser) ?

**Comment by inillaug** [comment]
Here the file...

[Simple.zip](https://github.com/manatlan/guy/files/4339838/Simple.zip)

**Comment by manatlan** [comment]
thanks ...
![Capture du 2020-03-16 20-38-33](https://user-images.githubusercontent.com/150722/76793936-51b19700-67c6-11ea-8c9c-65ec0685ed87.png)

Your file is well encoded (content is really utf8, and declared as utf8)
It works like expected ...

here is my test
```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
import guy

class Simple(guy.Guy):
    pass

if __name__ == "__main__":
    Simple().run()
```
what's the trouble ?

**Comment by inillaug** [comment]
![myresult](https://user-images.githubusercontent.com/59029709/76848609-4735e280-6844-11ea-8f70-3ace5e0c42c3.png)

Above my result with your python test code.
The OS is WIN7 64bit
Python is 3.6.8 64bit

**Comment by manatlan** [comment]
Strange ... and your chrome version ?

**Comment by inillaug** [comment]
Google Chrome Version 80.0.3987.132

**Comment by manatlan** [comment]
In the real world, your browser should see that the page is UT8 (according the meta declaration), and display it as ... UTF8.
But in your case: it's clearly display it, as "Windows-1252" ... so it shows "Ã¨" instead of  "è".

I don't think it could be a windows trouble (not a py trouble too).

The only thing: perhaps have you forced your Chrome to display all pages as "Windows-1252" ... BTW, i don't find how to set this in current chrome settings (it seems that the easy option has been removed) ... or perhaps you have a chrome extension which override defaults ?!?

I will think/search about it .. and come back later with an idea ;-)

**Comment by manatlan** [comment]
https://support.google.com/chrome/forum/AAAAP1KN0B02JIo6Yu7K-I/?hl=en&gpf=%23!topic%2Fchrome%2F2JIo6Yu7K-I

**Comment by inillaug** [comment]
If I run the code in "server mode" and I open the webpage in firefox or IE the trouble is the same.
If I open the file "Simple.html" directly in firefox, IE, chrome the webpage is rendered correctly without trouble. Anyway I'll test your suggestion.

**Comment by manatlan** [comment]
and if you visit : https://a-starlette.glitch.me/spe
what do you see ?

you should see:
![Capture du 2020-03-17 18-19-08](https://user-images.githubusercontent.com/150722/76883068-d90d1200-687b-11ea-83ff-27304dda36b4.png)

**Comment by inillaug** [comment]
I saw exactly wath you saw.

**Comment by manatlan** [comment]
So, it can't be a trouble in your browser.

Run my test ^^, in server mode, and try to point your browser to your real IP --> http://<YOUR IP>:8000 (replace "localhost" by your real IP)

**Comment by inillaug** [comment]
I already did this test.
If I run the code in "server mode" and I open the webpage in firefox, IE, chrome the trouble is the same.

**Comment by inillaug** [comment]
I did all test executed before in win7 on a win10 machine with the same trouble.

**Comment by manatlan** [comment]
on monday, I will have access to a win10/py3.7+latest chrome ...
I will have a test ... but if this was really a bug I'd already seen it

**Comment by inillaug** [comment]
I tested with win10/py3.7 and the trouble is the same. 
"Simple.html" loaded with apache shows correctly.

**Comment by inillaug** [comment]
The same code of Simple.html put in __doc__ string works correctly. 
See the attached py file.

[testmanatlanstring.zip](https://github.com/manatlan/guy/files/4362676/testmanatlanstring.zip)

**Comment by inillaug** [comment]
The trouble is in parsing the file to string. See this code....

[testmanatlanstringext.zip](https://github.com/manatlan/guy/files/4362696/testmanatlanstringext.zip)

**Comment by manatlan** [comment]
ok thanks @inillaug !
You have found the trouble !
It's my fault ... I thought that py3 known how to read a text file on "non-utf8" file system.
I apply a patch soon

**Comment by manatlan** [comment]
Please try the newest release : https://pypi.org/project/guy/0.5.4/
it should fix this issue

thanks a lot for your work !!!

**Comment by inillaug** [comment]
Version 0.5.4 fixed the issue. thanks a lot for your help!!
