### ISSUE TITLE
Failed to load "guy.js" from daughter html file

### ISSUE THREAD

**Issue by bendub** [manatlan/guy#7]
Hello Manatlan,
The client side of my app is composed of a main html file with a frame displaying "daughter html page".
The main html page can access the "guy.js" file when loaded but the daughter file can't i.e. when I inspect the page with Chromium DevTools, I found the following error:
``
GET http://localhost:39000/guy.js net::ERR_ABORTED 404 (Not Found)
``
I used guy v0.5.2.
Thank you

**Comment by manatlan** [comment]
Hi bendub ...
If I needed to make iframe, I'll do https://glitch.com/edit/#!/bendub?path=app.py:15:0 (source)
(demo: https://bendub.glitch.me/)

the main instance is the container .. and the iframe contains an instance of another guy's window.

**Comment by manatlan** [comment]
the same thing on repl.it : https://repl.it/@manatlan/bendub ;-)

**Comment by bendub** [comment]
Thank you very much Manatlan, everything seems OK for me now.
