### ISSUE TITLE
Error in doc

### ISSUE THREAD

**Issue by bendub** [manatlan/guy#9]
Hello Manatlan,
It seems there is an error in the documentation in part "async self.cfg" of "Server side" page.
It is mentioned: 

> To get a var 'name', in py side :
> name = await self.cfg.name

But when I used this syntax, it raises an error:

> TypeError: object str can't be used in 'await' expression

I prepare a test case with and without the use of 'await':
https://glitch.com/edit/#!/test-pycfg
Thank you.

**Comment by manatlan** [comment]
You've right !
I've missed something ;-) (btw I have (and I should) write pytests for this CORE feature)
I've made a test : https://glitch.com/edit/#!/guy-cfg?path=test_pycfg.py:25:0
(with add/show for client/server side) ... and it works as expected (but you're right, no need to await on server side)

**Comment by manatlan** [comment]
docs updated ! thx

**Comment by manatlan** [comment]
btw, I've just commited some pytest covering set/get cfg feature on client/server sides...
